language: erlang
sudo: false
otp_release:
# Test on all supported releases
   - 21.0
   - 20.3
   - 19.3
   - 18.3
   - 17.5

script:
  - make
  - rebar eunit -v skip_deps=true
  - make plt
  - make dialyze
notifications:
  email: false
